### ISSUE TITLE
Fix broken tests on 1.0.0

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisky#413]
### Description

Two tests are currently failing on the `1.0.0` branch, but not on CI: 

```
  1) broadcast signature command
       "before each" hook: setUpCommandBroadcastSignature for "Then it should not broadcast the signature":
     TypeError: Cannot stub non-existent own property broadcastSignatures
      at Object.stub (node_modules/sinon/lib/sinon/collection.js:99:19)
      at Context.setUpLiskJSAPIStubs (test/steps/setup.js:95:4)
      at Context.setUpCommandBroadcastSignature (test/steps/setup.js:189:22)

  2) broadcast transaction command
       "before each" hook: setUpCommandBroadcastTransaction for "Then it should not broadcast the transaction":
     TypeError: Cannot stub non-existent own property broadcastSignatures
      at Object.stub (node_modules/sinon/lib/sinon/collection.js:99:19)
      at Context.setUpLiskJSAPIStubs (test/steps/setup.js:95:4)
      at Context.setUpCommandBroadcastTransaction (test/steps/setup.js:194:22)
```

### Steps to Reproduce

`npm test` locally

**Expected behavior**

Tests should all pass. Failing tests should fail on CI.

**Comment by willclarktech** [comment]
@Tosch110 Local npm installation was out of sync with GitHub branch. Fix is to run `npm update`.

**Comment by Tosch110** [comment]
`npm update` did not work for me. I had to delete and redo the `package-lock.json`
