### ISSUE TITLE
4 tests fail when trying to push code

### ISSUE THREAD

**Issue by Mastermaulik** [LiskHQ/lisky#521]
### Description
4 tests from test/specs/helpers.js fail sometimes even when there is no change in code.
 
```
1029 passing (6s)
  4 failing

  1) create transaction cast votes
       Given a Vorpal instance with a UI and an active command that can prompt
         Given an action "create transaction cast votes"
           Given a Lisk object that can create transactions
             Given a passphrase "minute omit local rare sword knee banner pair rib museum shadow juice"
               Given a second passphrase "fame spoil quiz garbage mirror envelope island rapid lend year bike adapt"
                 Given public keys that should be voted for "215b667a32a5cd51a94c9c2046c11fffb08c65748febec099451e3b164452bca", "922fbfdd596fa78269bbcadc67ec2a1cc15fc929a19c462169568d7a3df1a1aa"
                   Given public keys that should be unvoted for "e01b6b8a9b808ec3f67a638a2d3fa0fe1a9439b91dbdde92e2839c3327bd4589", "ac09bc40c889f688f9158cca1fcfcdf6320f501242e0f7088d52a5077084ccba"
                     Given the passphrase can be retrieved from its source
                       Given an options object with votes set to "215b667a32a5cd51a94c9c2046c11,922fbfdd596fa78269bbcadc67ec"
                         When the action is called with the options
                           Then it should reject with validation error and message "Error processing public key 215b667a32a5cd51a94c9c2046c11: Invalid hex string.":

      AssertionError: expected '\u001b[31mPublic key 215b667a32a5cd51a94c9c2046c11 length differs from the expected 64 hex characters for a public key.\u001b[39m' to equal '\u001b[31mError processing public key 215b667a32a5cd51a94c9c2046c11: Invalid hex string.\u001b[39m'
      + expected - actual

      -Public key 215b667a32a5cd51a94c9c2046c11 length differs from the expected 64 hex characters for a public key.
      +Error processing public key 215b667a32a5cd51a94c9c2046c11: Invalid hex string.

      at Proxy.handleAssert (test/setup.js:46:32)
      at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:289:22)
      at Proxy.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:255:20)
      at Proxy.overwritingMethodWrapper (node_modules/chai/lib/chai/utils/overwriteMethod.js:78:33)
      at test/steps/general/3_then.js:120:21
      at <anonymous>

  2) create transaction cast votes
       Given a Vorpal instance with a UI and an active command that can prompt
         Given an action "create transaction cast votes"
           Given a Lisk object that can create transactions
             Given a passphrase "minute omit local rare sword knee banner pair rib museum shadow juice"
               Given a second passphrase "fame spoil quiz garbage mirror envelope island rapid lend year bike adapt"
                 Given public keys that should be voted for "215b667a32a5cd51a94c9c2046c11fffb08c65748febec099451e3b164452bca", "922fbfdd596fa78269bbcadc67ec2a1cc15fc929a19c462169568d7a3df1a1aa"
                   Given public keys that should be unvoted for "e01b6b8a9b808ec3f67a638a2d3fa0fe1a9439b91dbdde92e2839c3327bd4589", "ac09bc40c889f688f9158cca1fcfcdf6320f501242e0f7088d52a5077084ccba"
                     Given the passphrase can be retrieved from its source
                       Given an options object with unvotes set to "215b667a32a5cd51a94c9c2046c11,922fbfdd596fa78269bbcadc67ec"
                         When the action is called with the options
                           Then it should reject with validation error and message "Error processing public key 215b667a32a5cd51a94c9c2046c11: Invalid hex string.":

      AssertionError: expected '\u001b[31mPublic key 215b667a32a5cd51a94c9c2046c11 length differs from the expected 64 hex characters for a public key.\u001b[39m' to equal '\u001b[31mError processing public key 215b667a32a5cd51a94c9c2046c11: Invalid hex string.\u001b[39m'
      + expected - actual

      -Public key 215b667a32a5cd51a94c9c2046c11 length differs from the expected 64 hex characters for a public key.
      +Error processing public key 215b667a32a5cd51a94c9c2046c11: Invalid hex string.

      at Proxy.handleAssert (test/setup.js:46:32)
      at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:289:22)
      at Proxy.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:255:20)
      at Proxy.overwritingMethodWrapper (node_modules/chai/lib/chai/utils/overwriteMethod.js:78:33)
      at test/steps/general/3_then.js:120:21
      at <anonymous>

  3) create transaction register multisignature account command
       Given a Vorpal instance with a UI and an active command that can prompt
         Given an action "create transaction register multisignature account"
           Given a Lisk object that can create transactions
             Given a passphrase "minute omit local rare sword knee banner pair rib museum shadow juice"
               Given a lifetime of 24 hours
                 Given a minimum of 2 signatures
                   Given a keysgroup with keys "+215b667a32a5cd51a94c9c2046c11fffb08c65748febec099451e3b164452bca"
                     Given an empty options object
                       When the action is called with the keysgroup, the lifetime, the minimum number of signatures and the options
                         Then it should reject with validation error and message "Error processing public key +215b667a32a5cd51a94c9c2046c11fffb08c65748febec099451e3b164452bca: Invalid hex string.":

      AssertionError: expected '\u001b[31mPublic key +215b667a32a5cd51a94c9c2046c11fffb08c65748febec099451e3b164452bca length differs from the expected 64 hex characters for a public key.\u001b[39m' to equal '\u001b[31mError processing public key +215b667a32a5cd51a94c9c2046c11fffb08c65748febec099451e3b164452bca: Invalid hex string.\u001b[39m'
      + expected - actual

      -Public key +215b667a32a5cd51a94c9c2046c11fffb08c65748febec099451e3b164452bca length differs from the expected 64 hex characters for a public key.
      +Error processing public key +215b667a32a5cd51a94c9c2046c11fffb08c65748febec099451e3b164452bca: Invalid hex string.

      at Proxy.handleAssert (test/setup.js:46:32)
      at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:289:22)
      at Proxy.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:255:20)
      at Proxy.overwritingMethodWrapper (node_modules/chai/lib/chai/utils/overwriteMethod.js:78:33)
      at test/steps/general/3_then.js:120:21
      at <anonymous>
      at runMicrotasksCallback (internal/process/next_tick.js:121:5)
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  4) utils helpers
       #validatePublicKeys
         Given invalid public keys "+647aac1e2df8a5c870499d7ddc82236b1e10936977537a3844a6b05ea33f9ef6"
           When validatePublicKeys is called with the public keys
             Then it should throw validation error "Error processing public key +647aac1e2df8a5c870499d7ddc82236b1e10936977537a3844a6b05ea33f9ef6: Invalid hex string.":

      AssertionError: expected '\u001b[31mPublic key +647aac1e2df8a5c870499d7ddc82236b1e10936977537a3844a6b05ea33f9ef6 length differs from the expected 64 hex characters for a public key.\u001b[39m' to equal '\u001b[31mError processing public key +647aac1e2df8a5c870499d7ddc82236b1e10936977537a3844a6b05ea33f9ef6: Invalid hex string.\u001b[39m'
      + expected - actual

      -Public key +647aac1e2df8a5c870499d7ddc82236b1e10936977537a3844a6b05ea33f9ef6 length differs from the expected 64 hex characters for a public key.
      +Error processing public key +647aac1e2df8a5c870499d7ddc82236b1e10936977537a3844a6b05ea33f9ef6: Invalid hex string.

      at Proxy.handleAssert (test/setup.js:46:32)
      at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:289:22)
      at Proxy.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:255:20)
      at Proxy.overwritingMethodWrapper (node_modules/chai/lib/chai/utils/overwriteMethod.js:78:33)
      at Context.itShouldThrowValidationError (test/steps/general/3_then.js:39:11)



--------------------------------------------------------|----------|----------|----------|----------|----------------|
File                                                    |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
--------------------------------------------------------|----------|----------|----------|----------|----------------|
All files                                               |    99.86 |      100 |      100 |    99.84 |                |
 src                                                    |      100 |      100 |      100 |      100 |                |
  exec_file.js                                          |      100 |      100 |      100 |      100 |                |
 src/commands                                           |      100 |      100 |      100 |      100 |                |
  broadcast_signature.js                                |      100 |      100 |      100 |      100 |                |
  broadcast_transaction.js                              |      100 |      100 |      100 |      100 |                |
  config.js                                             |      100 |      100 |      100 |      100 |                |
  create_account.js                                     |      100 |      100 |      100 |      100 |                |
  create_transaction_cast_votes.js                      |      100 |      100 |      100 |      100 |                |
  create_transaction_register_delegate.js               |      100 |      100 |      100 |      100 |                |
  create_transaction_register_multisignature_account.js |      100 |      100 |      100 |      100 |                |
  create_transaction_register_second_passphrase.js      |      100 |      100 |      100 |      100 |                |
  create_transaction_transfer.js                        |      100 |      100 |      100 |      100 |                |
  decrypt_message.js                                    |      100 |      100 |      100 |      100 |                |
  decrypt_passphrase.js                                 |      100 |      100 |      100 |      100 |                |
  encrypt_message.js                                    |      100 |      100 |      100 |      100 |                |
  encrypt_passphrase.js                                 |      100 |      100 |      100 |      100 |                |
  get.js                                                |      100 |      100 |      100 |      100 |                |
  list.js                                               |      100 |      100 |      100 |      100 |                |
  set.js                                                |      100 |      100 |      100 |      100 |                |
  show_copyright.js                                     |      100 |      100 |      100 |      100 |                |
  show_warranty.js                                      |      100 |      100 |      100 |      100 |                |
  sign_message.js                                       |      100 |      100 |      100 |      100 |                |
  verify_message.js                                     |      100 |      100 |      100 |      100 |                |
 src/utils                                              |    99.62 |      100 |      100 |     99.6 |                |
  api.js                                                |      100 |      100 |      100 |      100 |                |
  config.js                                             |      100 |      100 |      100 |      100 |                |
  constants.js                                          |      100 |      100 |      100 |      100 |                |
  cryptography.js                                       |      100 |      100 |      100 |      100 |                |
  error.js                                              |      100 |      100 |      100 |      100 |                |
  fs.js                                                 |      100 |      100 |      100 |      100 |                |
  helpers.js                                            |    98.78 |      100 |      100 |    98.67 |             25 |
  logger.js                                             |      100 |      100 |      100 |      100 |                |
  mnemonic.js                                           |      100 |      100 |      100 |      100 |                |
  options.js                                            |      100 |      100 |      100 |      100 |                |
  print.js                                              |      100 |      100 |      100 |      100 |                |
  query.js                                              |      100 |      100 |      100 |      100 |                |
  tablify.js                                            |      100 |      100 |      100 |      100 |                |
  transactions.js                                       |      100 |      100 |      100 |      100 |                |
 src/utils/input                                        |      100 |      100 |      100 |      100 |                |
  index.js                                              |      100 |      100 |      100 |      100 |                |
  utils.js                                              |      100 |      100 |      100 |      100 |                |
--------------------------------------------------------|----------|----------|----------|----------|----------------|
npm ERR! code ELIFECYCLE
npm ERR! errno 4
npm ERR! lisky@1.0.0-beta.2 test:local: `NODE_ENV=test nyc mocha test/specs`
npm ERR! Exit status 4
npm ERR!
npm ERR! Failed at the lisky@1.0.0-beta.2 test:local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mauliksoneji/.npm/_logs/2018-05-09T18_12_57_778Z-debug.log
npm ERR! Test failed.  See above for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lisky@1.0.0-beta.2 prepush: `npm run lint && npm test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lisky@1.0.0-beta.2 prepush script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mauliksoneji/.npm/_logs/2018-05-09T18_12_57_819Z-debug.log
```

### Steps to Reproduce

1. Make some changes to any file. 
2. Run command `npm run test`

**Expected behavior:** [What you expect to happen]
The existing functionality shouldn't break as the helpers.js file is untouched.

**Actual behavior:** [What actually happens]
There are 4 test cases which fail due to which I am not able to push commits.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Very frequently when there are some changes made to the repository.

### Versions

1.0.0-beta.2

**Comment by shuse2** [comment]
Currently we only support node version `6.14.1`.
#435 is the issue regards to supporting multiple version of node.
